### ISSUE TITLE
How i can config change less to SASS?

### ISSUE THREAD

**Issue by cuongdevjs** [davidnguyen179/react-ssr-boilerplate#1]

**Comment by davidnguyen179** [comment]
What problem are u facing? Can u give me some description?

**Comment by cuongdevjs** [comment]
Current I read README, your repo using LESS. But I wanna use SASS instead of LESS? Possible to implement it?

**Comment by davidnguyen179** [comment]
This project is under development. Currently, I am not thinking of supporting the sass stuff. But I can show you the step to make at ur local environment

Great idea! After u set up using Sass, you can update the readme. What do u think?

**Comment by cuongdevjs** [comment]
Yeah. Thank you. What do i need to do to setup?

**Comment by davidnguyen11** [comment]
1. Uninstall `less-loader`
2. Install `sass-loader` and it's dependencies (Pls search)
3. Replace `less-loader` with `sass-loader`

https://github.com/davidnguyen179/react-ssr-boilerplate/blob/master/webpack/webpack.common.js#L80

4. Add `.sass` extension support at this line

https://github.com/davidnguyen179/react-ssr-boilerplate/blob/master/webpack/webpack.common.js#L10

5. Replace `.less` extension with `.sass` at this line

https://github.com/davidnguyen179/react-ssr-boilerplate/blob/master/index.js#L4

6. Replace `style.less` with `style.sass`, which you can find here

https://github.com/davidnguyen179/react-ssr-boilerplate/tree/master/src/components/button

Good luck!

**Comment by cuongdevjs** [comment]
Thanks for your support :)
